Adding submodule: extensions
Adding submodule: packager-extras
Adding submodule: cloud-server
Adding submodule: desktop
Adding submodule: docs
Adding submodule: scaffolding
Adding submodule: json
Adding submodule: scratch-audio
Adding submodule: scratch-paint
Adding submodule: scratch-storage
Adding submodule: mist
Adding submodule: scratch-render-fonts
Adding submodule: scratch-render
Adding submodule: scratch-svg-renderer
Adding submodule: types
Adding submodule: mirror
Adding submodule: paper.js
Adding submodule: scratch-parser
Adding submodule: scratch-translate-extension-languages-mirror
Adding submodule: unpackager
Adding submodule: nanolog
Adding submodule: docs
Adding submodule: scratch-gui
Adding submodule: scratch-blocks
Adding submodule: sb3fix
Adding submodule: trampoline
Adding submodule: turbowarp.org
Adding submodule: packager
Adding submodule: types-tw
Adding submodule: scratch-vm
Adding submodule: addons
Adding submodule: scratch-l10n
Adding submodule: winget-pkgs
Adding submodule: scratchblocks
All submodules added and updated.
